name: variables_management
on: 
  workflow_dispatch
env:
  WEEK_DAY: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        run: echo "$SALUDO, $NAME, Today is ${{env.WEEK_DAY}}! and ${{vars.RESEARCH_LLM_TABULAR}}"
        env:
          NAME: Dionis López
